spring:
  datasource:
    username: ${DATABASE_USER:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_KaeBFdS8LRzRZoOUiiv}
    url: ${DATABASE_URL:jdbc:mysql://mysql-28b663be-thabangsoulo-528d.k.aivencloud.com:13016/defaultdb?ssl-mode=REQUIRED}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # You can set this to 'validate' or 'none' if you don't want Hibernate to alter the database schema
logging:
  level:
    org:
      springframework:
        security: DEBUG
