spring:
  datasource:
    username: root
    password: ''
    url: jdbc:mysql://localhost:3306/ewealth
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG